services: 
  
  bookit.api:
    image: bookit.api
    container_name: BookIt.Api
    build:
      context: .
      dockerfile: src/BookIt.Api/Dockerfile
      args:
        configuration: "Development"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5050
      - ConnectionStrings__Database=Host=bookit-db;Port=5432;Database=bookit;Username=postgres;Password=postgres;
    ports:
      - "5051:5051"   # Exposes HTTP endpoint
      - "7123:7123"
    depends_on:
      - bookit-db
      
  bookit-db:
    image: postgres:latest
    container_name: BookIt.Db
    environment:
      - POSTGRES_DB=bookit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
